added three facts
Javanochka/m1-data-science-td pull request #37
Opened 2024-02-05 15:40 UTC by AmelieKnecht

.....

2024-02-05 15:45 UTC, Javanochka commented
Please, resolve your merge conflict :)

2024-02-05 15:55 UTC, Javanochka requested changes
There some problems here

2024-02-05 15:55 UTC, Javanochka commented on class01-git/facts.py
> +           facts=["I love chocolate", "I speak German", "I do Karate"])
Are you sure this code runs?

2024-02-09 11:21 UTC, Javanochka commented on class01-python/Exercise_sheet_1_func.ipynb
>    },
<pre class="ql-syntax" spellcheck="false">Line #4.        for i in list_of_goods:
</pre><p>We usually use i for indexes, and I recommend you to use more understandable variable names when they are not simple indexes. Here for example you have ingredients and their prices, and you use only prices, so you can write</p><p> </p><pre class="ql-syntax" spellcheck="false">for _, price in list_of_goods:
</pre><p> </p><p>And then refer just to the price. </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Javanochka/m1-data-science-td/pull/37/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='5'/>

2024-02-09 11:21 UTC, Javanochka commented on class01-python/Exercise_sheet_1_func.ipynb
>    },
<pre class="ql-syntax" spellcheck="false">Line #5.        for k, lst in dico_of_expenses.items():
</pre><p>k refers to the name of the person,  let's make our variables more readable. </p><p> </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Javanochka/m1-data-science-td/pull/37/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='15'/>

2024-02-09 11:21 UTC, Javanochka commented on class01-python/Exercise_sheet_1_func.ipynb
>    },
<pre class="ql-syntax" spellcheck="false">Line #1.    recipes_dico = {'recipe1': {'recipe': {'banana_bread': (20, 40, 3)}, 
</pre><p> </p><p>You do not follow the format here. The reason to why I ask you to define recipes first and ingredients  (and other stuff) separately is so that the information would not be repeated.  Currently you have information about carrefour repeated way too many times :) Please, recreate the dictionary :)</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Javanochka/m1-data-science-td/pull/37/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='19'/>

2024-02-09 11:21 UTC, Javanochka commented on class01-python/Exercise_sheet_1_func.ipynb
>    },
<pre class="ql-syntax" spellcheck="false">Line #4.    	for rec in dictionary_recipes:
</pre><p>If you have created the dictionary the right way you would also not need a bunch of extra for cycles :)</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Javanochka/m1-data-science-td/pull/37/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='23'/>

2024-02-09 11:21 UTC, Javanochka commented on class01-python/Exercise_sheet_1_func.ipynb
>    },
<pre class="ql-syntax" spellcheck="false">Line #1.    def sunday(dictionary_recipes):
</pre><p> </p><p>First, starting from here, I do not want to verify that everything is done correctly because your code becomes too complicated as you have chosen the wrong representation for the data. Also, you can always have examples of the output of your code in next cells  :) </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Javanochka/m1-data-science-td/pull/37/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='26'/>

2024-02-09 11:21 UTC, Javanochka commented on class01-python/Exercise_sheet_2_oop.ipynb
>    },
<pre class="ql-syntax" spellcheck="false">Line #11.    		if self.balance &gt; amount:
</pre><p>It's ok if you have exactly the amount of money in your bank account. 0 money left is aloud to be left in your account </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Javanochka/m1-data-science-td/pull/37/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='4'/>

2024-02-09 11:21 UTC, Javanochka commented on class01-python/Exercise_sheet_2_oop.ipynb
>    },
<pre class="ql-syntax" spellcheck="false">Line #24.    		return f'{self.name}, born on {self.birthdate}, account {self.account_number}, {self.balance}€'
</pre><p> </p><p>Your string is not the same as asked in the task </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Javanochka/m1-data-science-td/pull/37/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='8'/>

2024-02-09 11:21 UTC, Javanochka commented on class01-python/Exercise_sheet_2_oop.ipynb
>    },
<pre class="ql-syntax" spellcheck="false">Line #16.    	def change(self, amount):
</pre><p>This function does not have to update the banknotes in the ATM. It just computes the needed ones. </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Javanochka/m1-data-science-td/pull/37/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='14'/>

2024-02-09 11:21 UTC, Javanochka commented on class01-python/Exercise_sheet_2_oop.ipynb
>    },
<pre class="ql-syntax" spellcheck="false">Line #40.    	def debit(self, account_number, amount):
</pre><p>Ideally you should call method change here, so that to not do the same logic twice. </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Javanochka/m1-data-science-td/pull/37/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='16'/>

2024-02-09 11:21 UTC, Javanochka commented on class01-python/Exercise_sheet_2_oop.ipynb
>    },
<pre class="ql-syntax" spellcheck="false">Line #59.    	def run(self):
</pre><p>This code only allows you to run one verification for one user. The idea is to make a full CLI application here. So you make something similar to what I did in the git task <code>facts.py</code>.  <span class="ql-cursor">﻿</span></p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Javanochka/m1-data-science-td/pull/37/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='19'/>

2024-02-09 11:21 UTC, Javanochka commented on class01-python/Exercise_sheet_2_oop.ipynb
>    },
<pre class="ql-syntax" spellcheck="false">Line #5.    	def push(self, l:list):
</pre><p>Why does it take a list as a parameter? You just want to add one element, it doesn't have to be of any specific type.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Javanochka/m1-data-science-td/pull/37/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='27'/>

2024-02-09 11:21 UTC, Javanochka commented on class01-python/Exercise_sheet_2_oop.ipynb
>    },
<pre class="ql-syntax" spellcheck="false">Line #3.    		self.memory = memory 
</pre><p>You don't have to pass your memory, you will new to create a new Stack object here. By default the memory is empty and it's ok.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Javanochka/m1-data-science-td/pull/37/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='29'/>

2024-02-09 11:21 UTC, Javanochka commented on class01-python/Exercise_sheet_2_oop.ipynb
>    },
<pre class="ql-syntax" spellcheck="false">Line #11.    			ex_list.append(el)
</pre><p>This list will be an exact copy of the input list. Why do you do that?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Javanochka/m1-data-science-td/pull/37/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='29'/>

2024-02-09 11:21 UTC, Javanochka commented on class01-python/Exercise_sheet_2_oop.ipynb
>    },
<pre class="ql-syntax" spellcheck="false">Line #15.    				val = self.memory.push(ex_list)
</pre><p>So, here you will have to push just your current value. </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Javanochka/m1-data-science-td/pull/37/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='29'/>

2024-02-09 18:06 UTC, AmelieKnecht commented on class01-python/Exercise_sheet_2_oop.ipynb
>    },
<p>I call the method in lines 45 -47. Where do you mean I should call it otherwise?</p>

2024-02-09 19:21 UTC, Javanochka commented on class01-python/Exercise_sheet_2_oop.ipynb
>    },
<p>Oh, sorry. Hm, somehow I remember this code to be different. However, you still call the same function thrice, when you could do it only once. And also I have just noticed in line 42 -- you would want to verify that you have enough banknotes of each value. </p>

2024-02-21 16:23 UTC, closed without merging